version: '3.1'

services:
  db:
    image: postgres:11.5
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_DB: "${DB_NAME}"
    networks:
      - app
    ports:
      - 5432:5432
    restart: always

  app:
    build: .
    ports:
      - 2302:2302
    networks:
      - app
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app/

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    env_file:
      - .env
    networks:
      - app

networks:
  app:
    driver: bridge